name: jacoco-generateAndUploadResults
description: generates the files for the the jacoco test(also creates an badge with the % of tested code) and uploads them to a branch


inputs:
    token:
        description: token for uploading to a repository
        required: true
    reports_path:
        description: reports path
        default: "target/my-reports/*"
        required: false
    branch_name:
        description: branch name were reports files will get pushed
        default: "reports"
        required: false
    minimum_coverage:
        description: minimum_coverage
        default: "90"
        required: false
    generate_svg:
        description: generate svg
        default: "true"
        required: false

runs:
    using: composite

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        
      - name: Test with Maven
        id: Maven-Test
        run: mvn clean test
        shell: bash


      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: target/my-reports/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ inputs.token }}
          skip_check_run: false
          minimum_coverage: ${{ inputs.minimum_coverage }}
          fail_below_threshold: false
          publish_only_summary: false


      - if: ${{ inputs.generate_svg }} == "true"
        name: create badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'Test coverage'
          status: ${{ steps.jacoco_reporter.outputs.coveragePercentageString }}
          path: badge.svg
          color: ${{
            steps.jacoco_reporter.outputs.coveragePercentage > 90 && 'green'              ||
            steps.jacoco_reporter.outputs.coveragePercentage > 80 && 'yellow,green'       ||
            steps.jacoco_reporter.outputs.coveragePercentage > 70 && 'yellow'             ||
            steps.jacoco_reporter.outputs.coveragePercentage > 60 && 'orange,yellow'      ||
            steps.jacoco_reporter.outputs.coveragePercentage > 50 && 'orange'             ||
            steps.jacoco_reporter.outputs.coveragePercentage > 40 && 'red,orange'         ||
            steps.jacoco_reporter.outputs.coveragePercentage > 30 && 'red,red,orange'     ||
            steps.jacoco_reporter.outputs.coveragePercentage > 20 && 'red,red,red,orange' ||
            'red' }}



      - name: Commit and Push Generated Files
        run: |
          git rm --cached -r .
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add -f badge.svg
          git add -f target/my-reports/
          
          git commit -m "Add generated files"
          git push --force origin HEAD:${{ inputs.branch_name }}
        
        shell: bash
