name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean test
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Badge Action
        uses: emibcn/badge-action@v2.0.2

      # Capture the generated files as artifacts
      - name: Capture Test Generated Files
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: target/my-reports/ # Adjust the path to match your generated files



      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
      - name: Commit and Push Generated Files
        run: |
          git config --global user.email $GH_USEREMAIL
          git config --global user.name $GH_USER
          
          git checkout -- src/
          rm -rf src
          git add src/
          git checkout -- .gitignore
          rm .gitignore
          git add .gitignore
          git checkout -- openTest.bat
          rm openTest.bat
          git add openTest.bat
          git checkout -- pom.xml
          rm pom.xml
          git add pom.xml
          git checkout -- README.md
          rm README.md
          
          git add target/my-reports/*
          git commit -m "Add generated files"
          git push --force https://$GH_TOKEN@github.com/$GH_USER/TP2-GestorEmails.git HEAD:reports
